### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by jriggs** [maximecb/noisecraft#79]
Windows 10
message clipped, but I think this is the relevant part
```
gyp ERR! node -v v14.15.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\joe\Desktop\noisecraft\node_modules\sqlite3\lib\binding\node-v83-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\Users\joe\Desktop\noisecraft\node_modules\sqlite3\lib\binding\node-v83-win32-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\joe\Desktop\noisecraft\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Windows_NT 10.0.19044
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\joe\\Desktop\\noisecraft\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" 
"--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\joe\Desktop\noisecraft\node_modules\sqlite3
node-pre-gyp ERR! node -v v14.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
```

Update to sqlite 5 in package.json allowed install to complete

`    "sqlite3": "5.0.0",`

great project, happy to submit a PR if it would help

**Comment by maximecb** [comment]
Thanks @jriggs. You're saying a more recent version of sqlite3 works fine on windows?

**Comment by maximecb** [comment]
Updated to the latest version 👍
